server:
  port: 8080
  address: 0.0.0.0
  session:
    timeout: 360000

security:
  basic:
    enabled: false

spring:
  data:
    mongodb:
      uri: mongodb://${MONGODB_HOST:localhost}:${MONGODB_PORT:27017}/synergy
