app:
  name: synergy-backend
  description: the backend of synergy

server:
  port: 80
  address: 0.0.0.0
  session:
    timeout: 360000

security:
  basic:
    enabled: false

spring:
  mvc:
    date-format: yyyy-MM-dd
    favicon:
      enabled: false
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.sss'Z'
    serialization:
      write-dates-as-timestamps: true
  profiles:
    active: prd
