app:
  name: synergy-backend
  description: the backend of synergy

synergy:
  account:
    administrator:
      username: administrator
      password: change_me
      telephone: 13000000000
      email: administrator@changeme.com
    password:
      salt: '@account.synergy.clouthink.in'

logging:
  file: /Users/dz/var/synergy/log/openapi.log
  level:
    in.clouthink.synergy: DEBUG

server:
  port: 8081
  address: 0.0.0.0
  session:
    timeout: 360000

spring:
  mvc:
    date-format: yyyy-MM-dd
    favicon:
      enabled: false
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.sss'Z'
    serialization:
      write-dates-as-timestamps: true
  data:
    mongodb:
      uri: mongodb://${MONGODB_HOST:localhost}:${MONGODB_PORT:27017}/synergy
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    pool:
      max-active: 100
      max-idle: 8
      max-wait: 60000
  session:
    store-type: redis
    redis:
      namespace: openapi

multipart:
  enabled: true
  max-file-size: 20Mb
  max-request-size: 20Mb


####################### jmx configuration #######################

management:
  port: 1099
  context-path: /jmx

endpoints:
  enabled: false
  health:
    enabled: true

####################### eureka configuration #######################
eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOST:localhost}
    non-secure-port: ${EUREKA_INSTANCE_PORT:8080}
    prefer-ip-address: false
#    statusPageUrlPath: ${server.servletPath}/info
#    healthCheckUrlPath: ${server.servletPath}/health
#    statusPageUrl: https://${eureka.instance.hostname}/info
#    healthCheckUrl: https://${eureka.instance.hostname}/health
#    homePageUrl: https://${eureka.instance.hostname}/
    instance-id: ${spring.application.name}:${eureka.instance.hostname}:${eureka.instance.non-secure-port}:${random.value}
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:'http://localhost:8761/eureka/'}
