server:
  port: 10000

io:
  picos:
    scb:
      support:
        cors:
           allowCredentials: true
           allowOrigin: "*"
           allowHeader: "*"
           allowMethod: "*"

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOST:localhost}
    non-secure-port: ${EUREKA_INSTANCE_PORT:10000}
    prefer-ip-address: false
#    instance-id: ${spring.application.name}:${eureka.instance.hostname}:${eureka.instance.non-secure-port}:${random.value}
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
       defaultZone: ${EUREKA_SERVICE_URL:'http://localhost:8761/eureka/'}
